// Generated by gencpp from file servo_control/ServoPosition.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_MESSAGE_SERVOPOSITION_H
#define SERVO_CONTROL_MESSAGE_SERVOPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control
{
template <class ContainerAllocator>
struct ServoPosition_
{
  typedef ServoPosition_<ContainerAllocator> Type;

  ServoPosition_()
    : position1(0.0)
    , position2(0.0)  {
    }
  ServoPosition_(const ContainerAllocator& _alloc)
    : position1(0.0)
    , position2(0.0)  {
  (void)_alloc;
    }



   typedef double _position1_type;
  _position1_type position1;

   typedef double _position2_type;
  _position2_type position2;





  typedef boost::shared_ptr< ::servo_control::ServoPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control::ServoPosition_<ContainerAllocator> const> ConstPtr;

}; // struct ServoPosition_

typedef ::servo_control::ServoPosition_<std::allocator<void> > ServoPosition;

typedef boost::shared_ptr< ::servo_control::ServoPosition > ServoPositionPtr;
typedef boost::shared_ptr< ::servo_control::ServoPosition const> ServoPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control::ServoPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control::ServoPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_control::ServoPosition_<ContainerAllocator1> & lhs, const ::servo_control::ServoPosition_<ContainerAllocator2> & rhs)
{
  return lhs.position1 == rhs.position1 &&
    lhs.position2 == rhs.position2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_control::ServoPosition_<ContainerAllocator1> & lhs, const ::servo_control::ServoPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_control::ServoPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::ServoPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::ServoPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::ServoPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::ServoPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::ServoPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control::ServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "447f297a244af47c60883d47a59bd156";
  }

  static const char* value(const ::servo_control::ServoPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x447f297a244af47cULL;
  static const uint64_t static_value2 = 0x60883d47a59bd156ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control::ServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control/ServoPosition";
  }

  static const char* value(const ::servo_control::ServoPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control::ServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position1\n"
"float64 position2\n"
;
  }

  static const char* value(const ::servo_control::ServoPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control::ServoPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position1);
      stream.next(m.position2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control::ServoPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control::ServoPosition_<ContainerAllocator>& v)
  {
    s << indent << "position1: ";
    Printer<double>::stream(s, indent + "  ", v.position1);
    s << indent << "position2: ";
    Printer<double>::stream(s, indent + "  ", v.position2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_MESSAGE_SERVOPOSITION_H
